import { MagnitudeInfo, SafetyGuide } from '@/types';

export const MAGNITUDE_SCALE: MagnitudeInfo[] = [
  {
    value: 1,
    label: 'Micro',
    description: 'Not felt except by very few under especially favorable conditions',
    effects: 'No damage. Detected only by seismographs.',
    frequency: 'Several million per year',
    color: '#BBF7D0',
    examples: ['Continuous microseismic activity', 'Mining blasts'],
  },
  {
    value: 2,
    label: 'Minor',
    description: 'Felt only by a few persons at rest, especially on upper floors',
    effects: 'No damage. Hanging objects may swing slightly.',
    frequency: 'Over one million per year',
    color: '#4ADE80',
    examples: ['Small local tremors', 'Quarry blasts'],
  },
  {
    value: 3,
    label: 'Minor',
    description: 'Felt quite noticeably by persons indoors',
    effects: 'No significant damage. Vibration similar to passing truck.',
    frequency: 'Over 100,000 per year',
    color: '#16A34A',
    examples: ['2011 Oklahoma (3.0)', '2019 New Jersey (3.1)'],
  },
  {
    value: 4,
    label: 'Light',
    description: 'Felt indoors by many, outdoors by few during the day',
    effects: 'Dishes, windows rattle. Walls make cracking sound. No structural damage.',
    frequency: 'About 15,000 per year',
    color: '#FCD34D',
    examples: ['2020 North Carolina (4.0)', '2018 Tennessee (4.4)'],
  },
  {
    value: 5,
    label: 'Moderate',
    description: 'Felt by nearly everyone; many awakened',
    effects: 'Some dishes, windows broken. Unstable objects overturned. Slight damage to poorly constructed buildings.',
    frequency: 'About 1,500 per year',
    color: '#FBBF24',
    examples: ['2011 Virginia (5.8)', '2020 North Carolina (5.1)'],
  },
  {
    value: 6,
    label: 'Strong',
    description: 'Felt by all; many frightened and run outdoors',
    effects: 'Considerable damage to poorly built structures. Slight to moderate damage in well-built buildings. Chimneys, factory stacks, monuments may fall.',
    frequency: 'About 150 per year',
    color: '#F59E0B',
    examples: ['2014 Napa, California (6.0)', '1994 Northridge (6.7)'],
  },
  {
    value: 7,
    label: 'Major',
    description: 'Difficult to stand. Noticed by drivers of cars',
    effects: 'Considerable damage to well-designed buildings. Ground cracks conspicuously. Underground pipes broken.',
    frequency: 'About 20 per year',
    color: '#F97316',
    examples: ['2010 Haiti (7.0)', '1989 Loma Prieta (7.1)'],
  },
  {
    value: 8,
    label: 'Great',
    description: 'Panic is general. Steering of cars greatly affected',
    effects: 'Severe damage to most buildings. Ground badly cracked. Large landslides. Tsunami possible.',
    frequency: 'About 1 per year',
    color: '#EF4444',
    examples: ['2015 Nepal (7.8)', '1906 San Francisco (7.9)'],
  },
  {
    value: 9,
    label: 'Great',
    description: 'Total panic. Objects thrown into the air',
    effects: 'Most buildings destroyed. Ground disturbances widespread. Large-scale liquefaction. Major tsunami.',
    frequency: 'About 1 per 20 years',
    color: '#DC2626',
    examples: ['2011 Tōhoku, Japan (9.1)', '2004 Indian Ocean (9.1)'],
  },
  {
    value: 10,
    label: 'Epic',
    description: 'Never recorded in modern history',
    effects: 'Total destruction. Waves seen on ground surface. Objects thrown into air. Massive changes to landscape.',
    frequency: 'Extremely rare',
    color: '#991B1B',
    examples: ['1960 Valdivia, Chile (9.5) - largest recorded'],
  },
];

export const SAFETY_GUIDES: SafetyGuide[] = [
  {
    id: 'eq-before-1',
    title: 'Prepare Your Home',
    category: 'before',
    eventType: 'earthquake',
    icon: 'home',
    steps: [
      'Secure heavy furniture, appliances, and tall objects to walls',
      'Store heavy items on lower shelves',
      'Install flexible pipe fittings to avoid gas or water leaks',
      'Know how to turn off gas, water, and electricity',
      'Repair defective electrical wiring and leaky gas connections',
      'Bolt down water heaters and gas appliances',
    ],
    sources: ['FEMA Ready.gov', 'USGS Earthquake Hazards Program'],
  },
  {
    id: 'eq-before-2',
    title: 'Build an Emergency Kit',
    category: 'before',
    eventType: 'earthquake',
    icon: 'package',
    steps: [
      'Water: 1 gallon per person per day for at least 3 days',
      'Non-perishable food for at least 3 days',
      'Battery-powered or hand-crank radio and NOAA Weather Radio',
      'Flashlight and extra batteries',
      'First aid kit and essential medications',
      'Whistle to signal for help',
      'Dust masks, plastic sheeting, and duct tape',
      'Wrench or pliers to turn off utilities',
      'Local maps and emergency contact information',
    ],
    sources: ['American Red Cross', 'FEMA'],
  },
  {
    id: 'eq-before-3',
    title: 'Make a Family Plan',
    category: 'before',
    eventType: 'earthquake',
    icon: 'users',
    steps: [
      'Identify safe spots in each room (under sturdy tables, against interior walls)',
      'Practice Drop, Cover, and Hold On drills',
      'Establish a family meeting place outside your home',
      'Choose an out-of-state contact person',
      'Learn first aid and CPR',
      'Keep important documents in a waterproof container',
      'Plan for pets and service animals',
    ],
    sources: ['FEMA Ready.gov', 'Earthquake Country Alliance'],
  },
  {
    id: 'eq-during-1',
    title: 'If You Are Indoors',
    category: 'during',
    eventType: 'earthquake',
    icon: 'shield-alert',
    steps: [
      'DROP to your hands and knees immediately',
      'COVER your head and neck under a sturdy table or desk',
      'HOLD ON to your shelter and be prepared to move with it',
      'Stay away from windows, mirrors, and heavy objects that could fall',
      'Do NOT run outside or to doorways',
      'If in bed, stay there and cover your head with a pillow',
      'Stay inside until shaking stops and it is safe to exit',
    ],
    sources: ['USGS', 'ShakeOut.org', 'American Red Cross'],
  },
  {
    id: 'eq-during-2',
    title: 'If You Are Outdoors',
    category: 'during',
    eventType: 'earthquake',
    icon: 'trees',
    steps: [
      'Move away from buildings, streetlights, and utility wires',
      'Drop to the ground and stay there until shaking stops',
      'If in a vehicle, pull over to a clear location and stop',
      'Avoid stopping near buildings, trees, overpasses, or utility wires',
      'Stay inside the vehicle with seatbelt fastened',
      'Proceed cautiously once shaking stops, avoiding bridges and ramps',
    ],
    sources: ['USGS', 'FEMA'],
  },
  {
    id: 'eq-during-3',
    title: 'Special Situations',
    category: 'during',
    eventType: 'earthquake',
    icon: 'alert-triangle',
    steps: [
      'In a stadium or theater: Stay in your seat and protect your head',
      'Near the shore: Drop, Cover, Hold On, then move inland to higher ground',
      'In a high-rise: Drop, Cover, Hold On. Do not use elevators',
      'In a wheelchair: Lock wheels and cover head and neck',
      'In a store: Move away from shelves with heavy items',
    ],
    sources: ['Earthquake Country Alliance', 'USGS'],
  },
  {
    id: 'eq-after-1',
    title: 'Immediate Actions',
    category: 'after',
    eventType: 'earthquake',
    icon: 'check-circle',
    steps: [
      'Check yourself and others for injuries. Provide first aid',
      'Check for fires, fire hazards, and other household hazards',
      'If you smell gas or hear hissing, open windows and leave immediately',
      'Turn off utilities if damaged',
      'Listen to a battery-powered radio for emergency information',
      'Stay out of damaged buildings',
      'Be careful of broken glass and debris',
      'Expect aftershocks - Drop, Cover, Hold On during each one',
    ],
    sources: ['USGS', 'FEMA', 'American Red Cross'],
  },
  {
    id: 'eq-after-2',
    title: 'Inspect Your Home',
    category: 'after',
    eventType: 'earthquake',
    icon: 'search',
    steps: [
      'Check for structural damage before re-entering',
      'Look for cracks in the foundation, walls, and chimney',
      'Check for gas leaks, damaged electrical wiring, and water line damage',
      'Clean up spilled medicines, bleach, gasoline, and other flammable liquids',
      'Take photos of damage for insurance claims',
      'If home is unsafe, do not enter until cleared by authorities',
    ],
    sources: ['FEMA', 'American Red Cross'],
  },
  {
    id: 'eq-after-3',
    title: 'Recovery and Communication',
    category: 'after',
    eventType: 'earthquake',
    icon: 'phone',
    steps: [
      'Use text messages or social media to communicate (phone lines may be overloaded)',
      'Stay off the roads unless absolutely necessary',
      'Keep streets clear for emergency vehicles',
      'Register with disaster relief services',
      'Document property damage with photos',
      'Contact your insurance company',
      'Be patient - recovery takes time',
    ],
    sources: ['FEMA', 'American Red Cross'],
  },
  {
    id: 'volcano-before-1',
    title: 'Know Your Risk',
    category: 'before',
    eventType: 'volcano',
    icon: 'mountain',
    steps: [
      'Learn about your community\'s warning systems and evacuation plans',
      'Know if you live in a lahar (mudflow) hazard zone',
      'Identify evacuation routes and shelter locations',
      'Prepare an emergency kit with N95 masks or respirators',
      'Keep goggles and protective clothing available',
      'Have a plan for livestock and pets',
    ],
    sources: ['USGS Volcano Hazards Program', 'FEMA'],
  },
  {
    id: 'volcano-during-1',
    title: 'During Ashfall',
    category: 'during',
    eventType: 'volcano',
    icon: 'cloud',
    steps: [
      'Stay indoors and close all windows and doors',
      'Wear N95 masks or use damp cloth over nose and mouth',
      'Wear goggles to protect eyes from ash',
      'Keep skin covered with long sleeves and pants',
      'Avoid driving unless absolutely necessary',
      'If you must drive, use headlights and drive slowly',
      'Bring pets and livestock into shelters',
      'Do not run air conditioning or fans that bring outside air inside',
    ],
    sources: ['USGS', 'CDC', 'WHO'],
  },
  {
    id: 'volcano-during-2',
    title: 'During Evacuation',
    category: 'during',
    eventType: 'volcano',
    icon: 'move',
    steps: [
      'Follow evacuation orders immediately',
      'Take your emergency kit and important documents',
      'Wear long-sleeved shirts and long pants',
      'Use goggles and a mask or damp cloth over your face',
      'Stay out of designated restricted zones',
      'Avoid river valleys and low-lying areas (lahar risk)',
      'Listen to emergency broadcasts for updates',
    ],
    sources: ['USGS', 'FEMA'],
  },
  {
    id: 'volcano-after-1',
    title: 'After Eruption',
    category: 'after',
    eventType: 'volcano',
    icon: 'shield-check',
    steps: [
      'Wait for official clearance before returning home',
      'Continue wearing protective gear when outside',
      'Clear roofs of ash (it is very heavy and can cause collapse)',
      'Avoid getting ash in water supplies, machinery, and electronics',
      'Wash ash off with water, not compressed air',
      'Watch for mudflows and flooding',
      'Stay away from areas downwind of the volcano',
      'Seek medical attention for breathing difficulties',
    ],
    sources: ['USGS', 'CDC', 'FEMA'],
  },
  {
    id: 'volcano-after-2',
    title: 'Health Precautions',
    category: 'after',
    eventType: 'volcano',
    icon: 'heart-pulse',
    steps: [
      'Limit outdoor activities if ash is falling',
      'People with respiratory conditions should stay indoors',
      'Drink only bottled or covered stored water',
      'Wash vegetables and fruits thoroughly',
      'Keep ash out of your home as much as possible',
      'If you have asthma or respiratory issues, follow your treatment plan',
      'Seek medical care if you have difficulty breathing or eye irritation',
    ],
    sources: ['CDC', 'WHO', 'USGS'],
  },
];

export const TSUNAMI_WARNING_INFO = {
  title: 'Tsunami Warning',
  description: 'This earthquake may have generated a tsunami. If you are near the coast:',
  steps: [
    'Move inland to higher ground immediately',
    'Stay at least 100 feet above sea level or 2 miles inland',
    'Do NOT wait for official warnings',
    'Stay away from the beach and coastal areas',
    'Listen to emergency broadcasts',
    'Do not return until authorities say it is safe',
  ],
  sources: ['NOAA Tsunami Warning Center', 'USGS'],
};

export const TSUNAMI_SAFETY_GUIDES: SafetyGuide[] = [
  {
    id: 'tsunami-before-1',
    title: 'Know the Warning Signs',
    category: 'before',
    eventType: 'both',
    icon: 'alert-triangle',
    steps: [
      'Learn to recognize natural tsunami warnings: strong earthquake, unusual ocean behavior',
      'If you feel a strong earthquake lasting 20+ seconds near the coast, move to high ground immediately',
      'Watch for sudden ocean withdrawal (water receding unusually far from shore)',
      'Listen for a loud roar similar to a train or jet aircraft coming from the ocean',
      'Know your community\'s tsunami evacuation routes and shelter locations',
      'Sign up for local emergency alerts and tsunami warning systems',
      'Identify high ground at least 100 feet above sea level or 2 miles inland',
    ],
    sources: ['NOAA Tsunami Warning Center', 'FEMA', 'UNESCO IOC'],
  },
  {
    id: 'tsunami-before-2',
    title: 'Prepare Your Family',
    category: 'before',
    eventType: 'both',
    icon: 'users',
    steps: [
      'Create a family emergency plan with meeting points on high ground',
      'Practice tsunami evacuation drills with your family',
      'Prepare a "go bag" with essentials: water, food, medications, documents',
      'Keep important documents in waterproof containers',
      'Know where your children spend time (school, daycare) and their evacuation plans',
      'Plan for pets - know which shelters accept animals',
      'Keep your car fueled if you live in a tsunami hazard zone',
    ],
    sources: ['NOAA', 'American Red Cross', 'FEMA'],
  },
  {
    id: 'tsunami-before-3',
    title: 'Understand Your Risk',
    category: 'before',
    eventType: 'both',
    icon: 'map',
    steps: [
      'Check if you live, work, or travel in a tsunami hazard zone',
      'Coastal areas, especially near subduction zones, are at highest risk',
      'Tsunamis can travel up rivers and streams that lead to the ocean',
      'Low-lying coastal areas are vulnerable even if far from earthquake epicenter',
      'Review tsunami hazard maps for your area',
      'Understand that tsunamis can arrive within minutes of a nearby earthquake',
      'Know that distant earthquakes can also generate tsunamis hours later',
    ],
    sources: ['NOAA Tsunami Warning Center', 'USGS', 'UNESCO IOC'],
  },
  {
    id: 'tsunami-during-1',
    title: 'If You Feel an Earthquake Near the Coast',
    category: 'during',
    eventType: 'both',
    icon: 'alert-circle',
    steps: [
      'DROP, COVER, and HOLD ON during the earthquake',
      'As soon as shaking stops, move immediately to high ground',
      'Do NOT wait for an official tsunami warning',
      'Move quickly on foot - do not drive unless absolutely necessary',
      'Head inland and uphill - get at least 100 feet above sea level or 2 miles inland',
      'If you cannot reach high ground, go to the upper floors of a sturdy building',
      'Stay away from the beach, harbors, and coastal areas',
    ],
    sources: ['NOAA', 'USGS', 'FEMA'],
  },
  {
    id: 'tsunami-during-2',
    title: 'If You See Natural Warning Signs',
    category: 'during',
    eventType: 'both',
    icon: 'eye',
    steps: [
      'If you see the ocean receding unusually, evacuate immediately',
      'If you hear a loud roar from the ocean, move to high ground at once',
      'Do NOT go to the beach to watch the tsunami',
      'Do NOT wait to see the wave - by then it may be too late',
      'Move quickly and calmly - do not panic but act with urgency',
      'Help others evacuate, especially elderly, children, and people with disabilities',
      'Leave belongings behind - your life is more important',
    ],
    sources: ['NOAA Tsunami Warning Center', 'UNESCO IOC'],
  },
  {
    id: 'tsunami-during-3',
    title: 'If You Receive an Official Warning',
    category: 'during',
    eventType: 'both',
    icon: 'radio',
    steps: [
      'Evacuate immediately if you are in a tsunami hazard zone',
      'Follow designated evacuation routes to high ground',
      'Listen to emergency broadcasts for updates and instructions',
      'Do NOT return to coastal areas until authorities declare it safe',
      'Stay informed - tsunamis are a series of waves, not just one',
      'The first wave may not be the largest - subsequent waves can be bigger',
      'Tsunami waves can continue for hours after the first arrival',
    ],
    sources: ['NOAA', 'FEMA', 'Local Emergency Management'],
  },
  {
    id: 'tsunami-during-4',
    title: 'If Caught in a Tsunami',
    category: 'during',
    eventType: 'both',
    icon: 'life-buoy',
    steps: [
      'If caught in tsunami waters, grab onto something that floats',
      'Climb onto debris if possible to stay above water',
      'Protect your head from debris and impacts',
      'Try to avoid power lines and electrical wires',
      'Do NOT try to swim against the current',
      'Hold on and wait for the water to recede',
      'Call for help when safe to do so',
    ],
    sources: ['NOAA', 'American Red Cross', 'UNESCO IOC'],
  },
  {
    id: 'tsunami-after-1',
    title: 'Stay Safe After the Waves',
    category: 'after',
    eventType: 'both',
    icon: 'shield-check',
    steps: [
      'Stay on high ground - do NOT return to coastal areas for several hours',
      'Wait for official "all clear" from authorities before returning',
      'Remember: tsunamis are a series of waves that can last for hours',
      'Later waves may be larger than the first wave',
      'Stay away from debris in the water and on shore',
      'Avoid floodwaters - they may be contaminated or electrically charged',
      'Listen to emergency broadcasts for updates and instructions',
    ],
    sources: ['NOAA Tsunami Warning Center', 'FEMA'],
  },
  {
    id: 'tsunami-after-2',
    title: 'Returning Home Safely',
    category: 'after',
    eventType: 'both',
    icon: 'home',
    steps: [
      'Wait for authorities to declare it safe before returning home',
      'Be cautious of structural damage to buildings',
      'Watch for loose power lines, gas leaks, and damaged utilities',
      'Do NOT enter buildings if you smell gas or see damage',
      'Take photos of damage for insurance claims',
      'Avoid drinking tap water until authorities say it is safe',
      'Clean and disinfect everything that got wet',
      'Watch for animals (snakes, insects) that may have been displaced',
    ],
    sources: ['FEMA', 'American Red Cross', 'CDC'],
  },
  {
    id: 'tsunami-after-3',
    title: 'Health and Recovery',
    category: 'after',
    eventType: 'both',
    icon: 'heart-pulse',
    steps: [
      'Seek medical attention for any injuries',
      'Avoid contact with floodwater - it may contain sewage, chemicals, or debris',
      'Wash hands frequently, especially before eating',
      'Throw away food that came in contact with floodwater',
      'Watch for signs of stress and trauma in yourself and family members',
      'Reach out for mental health support if needed',
      'Document losses and contact your insurance company',
      'Register with disaster relief services for assistance',
    ],
    sources: ['CDC', 'FEMA', 'American Red Cross', 'WHO'],
  },
];

export const MMI_SCALE = [
  { level: 1, label: 'Not felt', description: 'Not felt except by very few' },
  { level: 2, label: 'Weak', description: 'Felt by few, especially on upper floors' },
  { level: 3, label: 'Weak', description: 'Felt noticeably indoors' },
  { level: 4, label: 'Light', description: 'Felt by many indoors, few outdoors' },
  { level: 5, label: 'Moderate', description: 'Felt by nearly everyone' },
  { level: 6, label: 'Strong', description: 'Felt by all, many frightened' },
  { level: 7, label: 'Very Strong', description: 'Difficult to stand' },
  { level: 8, label: 'Severe', description: 'Steering of cars affected' },
  { level: 9, label: 'Violent', description: 'General panic' },
  { level: 10, label: 'Extreme', description: 'Most buildings destroyed' },
];
